### ISSUE TITLE
Gooooogle page numbers are selected instead of results 

### ISSUE THREAD

**Issue by Industry** [jchafik/google-search-shortcuts#25]
The plugin stopped working and now selects the page numbers on the bottom instead of the results themselves. There is no way using vim style navigation or arrow keys to select the search results. Also enabling "select the first result" makes the page jump to the bottom upon loading. Plugin does not work at the moment, and had to be disabled.

**Comment by jchafik** [comment]
Google updated their selectors. A new version has been released and should be available shortly.

**Comment by myfonj** [comment]
Is `v1.1.15` really working for you folks?

I've been getting *some* "main" results that were omitted by this extension for some time, but now (perhaps since update to `v1.1.15`) it misses *all* of main results: So for example when I do https://www.google.com/search?q=test, "next result" shortcut jumps straight at the first item in "Related searches" block.
(Tried both when not logged-in and logged-in, and both in Chrome and Firefox.)

<img src="https://user-images.githubusercontent.com/1761395/124971673-c77bea80-e029-11eb-8af9-df11e4c24a60.png" width="200" alt="Focused item after first invocation of 'next result'.">

Maybe Google changed structure once again in short period of time? I've extracted what my Firefox sees in main content block of aforementioned search here:
https://gist.github.com/myfonj/385f790ddc5dc6bb1114821b466539f2

**Comment by buschtoens** [comment]
Same for me. #29 is my attempt to fix it.
