### ISSUE TITLE
Wildcard *.google.com access makes the extension less secure

### ISSUE THREAD

**Issue by kevlened** [jchafik/google-search-shortcuts#43]
This permission extends access beyond the search pages (to mail.google.com, calendar.google.com, etc), so I hesitated before installing. If the extension was only scoped to www.google.com, the potential damage would be limited if the extension were compromised.

**Comment by jchafik** [comment]
When the extension was first released, I had restricted access to `www.google.com`. However, at one point, the extension supported similar search domains such as `scholar.google.com`, `books.google.com`, etc. 

Since we're no longer supporting those subdomains, I've gone ahead and reverted the permissions.
